### ISSUE TITLE
Support XO not only as pure package

### ISSUE THREAD

**Issue by mrmlnc** [SamVerschueren/vscode-linter-xo#17]
Hello, @SamVerschueren,

New version solves many problems, but brings new. In previous versions i could use this extension if i had installed any package that contains XO. In the current version, can i use an extension only if the have XO in the dependencies.

For example:

![2016-07-19_17-51-15](https://cloud.githubusercontent.com/assets/7034281/16954399/6c78057a-4dd9-11e6-81e1-c8fc2992c559.gif)

It seems to me that have two dependencies is a bad idea (even with npm@3). This is a bug or a conscious decision?

English is not my native language, hope you can understand what i say.

**Comment by SamVerschueren** [comment]
@sindresorhus @wmertens feedback?

**Comment by wmertens** [comment]
Not depending on xo but using it is a mistake IMHO.

An option is to check if the xo property is set in the package.json, and then hoping xo will come from somewhere (perhaps even the linter package). This only works if there are no extra plugins defined, because they will depend on eslint and/or xo and will require you to install them anyway.

**Comment by SamVerschueren** [comment]
I'm with @wmertens  on this. I think it's not a good idea to not use XO directly as a dependency and still depend on it hoping that you'll never remove `gulp-xo`.

For instance, I might be depending on package `A` which in turns depends on package `B`. Because I know that, I might be able to `require('B');` while it is not in my dependency list. If `A` decides to swap out `B` for dependency `C`, my code will break.

I believe this is the same thing here. If `gulp-xo` decides to not directly depend on the `xo` package but on `eslint` + `eslint-config-xo` instead, your code won't be linted anymore.

**Comment by mrmlnc** [comment]
Thanks for the answers. I ask this because i use a local installation of the XO in the projects. In some projects, the XO is used as a plugin to Gulp and in previous version of this extension i don't need to have the pure package in the dependencies.

In the new version you added checks for [XO in the project dependencies](https://github.com/SamVerschueren/vscode-linter-xo/blob/master/xo-server/src/server.ts#L170-L173). I think that this is not a problem and i just replace Gulp plugin on a pure package.

I close this issue?

**Comment by SamVerschueren** [comment]
I'll do it, no problem :).
