### ISSUE TITLE
Finding the wrong tsconfig.json file

### ISSUE THREAD

**Issue by rizowski** [SamVerschueren/vscode-linter-xo#69]
If I have multiple instances of VS-Code open I will get the error: 

```
Parsing error: File '/file/path/first-instance-project/tsconfig.json' not found.
```

No matter how many vs-code instances I open, it is always looking in the first project's directory for the tsconfig file. I have to close all instances of vs-code and reopen that one project in order for it to find the correct file. Any other instances opened after that will have the issue again.

This seems related to #61

Similar issues:
https://github.com/SamVerschueren/vscode-linter-xo/issues/69#issuecomment-520980209

**Comment by jedmao** [comment]
I only have one instance of vscode open and I'm receiving a similar error:

> Parsing error: File 'C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\tsconfig.json' not found.XO

I have a `tsconfig.json` at project at root and others scattered throughout the project.

**Comment by herreraemanuel** [comment]
Look like the fix is not in the marketplace.

Left: Repo version
Right: Extension from the marketplace

![shot_190831_231401](https://user-images.githubusercontent.com/299113/64070964-89e7f280-cc45-11e9-8c0b-f0c238b1639b.png)

**Comment by markypython** [comment]
@SamVerschueren Can you release a new version of the extension to fix this issue?

**Comment by TheEdgyDev** [comment]
A _**very poor, yet functiona**l_ fix to this issue, in the meantime, is to configure XO within your `package.json` with a false path to your `tsconfig.json`. This false path must be relative to wherever this extension is wrongly searching for your `tsconfig.json` (_not relative to the actual `package.json` file_) where the destination is the true `tsconfig.json`.

For instance, on Ubuntu 18.04, this extension is searching in my user's home directory. If I had a subfolder of my home directory named `project`, where the `tsconfig.json` was, my package might look like the following:

```jsonc
{
    // ...
    "xo": {
        "extends": "xo-typescript",
	"extensions": [
	    "ts"
	],
	"parserOptions": {
	    "project": "./project/tsconfig.json"
	}
    }
}
```

**This will make xo invoked in any other way fail** since the relative path we've supplied _is very wrong_. This is, as said before, a  _very poor, yet functional_ fix for those who wish to have this extension work as expected.

**Comment by jeffryang24** [comment]
Dear @SamVerschueren, please release the new version for this extension to fix this issue. :bowing_man:

**Comment by yakov116** [comment]
@rizowski Can you try the latest version?

**Comment by Spence-S** [comment]
This was actually an xo issue that has been resolved in the latest release. since this issue is stale I am closing, but if anyone has any more TS problems with the latest xo installed please open a new one.
